version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 8080:8080/tcp # qBittorrent Web UI
      - 3000:3000/tcp # Webtop
      - 3001:3001/tcp # Webtop HTTPS
      # We don't expose the Torrent port (6881) here because it goes through the VPN tunnel, not the host network
    volumes:
      - ./gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
      
      # WireGuard Interface Config (OMAN)
      - WIREGUARD_PRIVATE_KEY=IFFgaSS3WT8aZ/szl+nBOZVvuj6HylUs9gq5jjmfrnE=
      - WIREGUARD_ADDRESSES=172.21.2.149/32
      
      # WireGuard Peer Config (OMAN)
      - WIREGUARD_PUBLIC_KEY=VIs/NY8w7ueAgd8c2lFlxq+Eg0ZqhiNVgIgJGRt2Mhc=
      - WIREGUARD_ENDPOINT_IP=172.94.96.3
      - WIREGUARD_ENDPOINT_PORT=51820
      - WIREGUARD_PERSISTENT_KEEPALIVE=21
      
      # DNS (OMAN)
      - DNS_ADDRESS=172.94.96.2
      
      # Firewall Ports for Torrenting
      - FIREWALL_VPN_INPUT_PORTS=6881
    restart: always

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - WEBUI_PORT=8080
    volumes:
      - ./qbittorrent/config:/config
      - /mnt/media/Downloads:/downloads
    restart: always

  webtop:
    image: lscr.io/linuxserver/webtop:latest
    container_name: webtop
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - ./webtop/config:/config
      - /mnt/media:/media
    shm_size: "1gb"
    restart: unless-stopped
